apiVersion: v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: eu.gcr.io/cpy-docker-test/api-gateway
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
              initialDelaySeconds: 30
        ports:
          - containerPort: 8080
      - name: kubectl
        image: "eu.gcr.io/google_containers/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty"
        imagePullPolicy: Always
        command:
          - proxy
        args:
          - -p
          - 8001


