apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    run: api-gateway-service
    resource: health
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: api-gateway-service
  type: LoadBalancer
