apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: eu.gcr.io/cpy-docker-test/api-gateway
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        ports:
        - containerPort: 8080
      - name: kubectl
        image: eu.gcr.io/google_containers/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty
        imagePullPolicy: Always
        args:
        - proxy
        - "-p"
        - '8001'


