apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      nodeSelector:
        "cloud.google.com/gke-nodepool": build-pool
      containers:
      - name: api-gateway
        image: eu.gcr.io/cpy-docker-test/api-gateway
        imagePullPolicy: Always
        env:
        - name: K8S_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: default-token-y6xrv
              key: token
        - name: K8S_API_HOST
          value: "kubernetes"
        - name: K8S_API_PORT
          value: "443"
        - name: AUTH_HOST
          value: "auth-service-service.default"
        - name: AUTH_PORT
          value: "80"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - containerPort: 8080
        - containerPort: 8081
